version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
      - DB_USER=flaskuser
      - DB_PASSWORD=root
      - DB_NAME=flaskapp
    depends_on:    
      - db

  db:
    image: mariadb:11
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
