CREATE DATABASE IF NOT EXISTS flaskapp;
CREATE USER IF NOT EXISTS 'flaskuser'@'%' IDENTIFIED BY 'yourpassword';
GRANT ALL PRIVILEGES ON flaskapp.* TO 'flaskuser'@'%';
FLUSH PRIVILEGES;

USE flaskapp;

CREATE TABLE IF NOT EXISTS Posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
    username VARCHAR(50) NOT NULL,
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL
);
